const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {onObjectFinalized,onObjectDeleted}=require('firebase-functions/v2/storage');
const {initializeApp}=require('firebase-admin/app');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue,Timestamp}=require('firebase-admin/firestore');
const {getStorage}=require('firebase-admin/storage');
const crypto=require('node:crypto');

initializeApp();
const db=getFirestore();
const REGION='us-central1';
const STORAGE_REGION='us-east1';
const STORAGE_BUCKET='studyloop-01.firebasestorage.app';
const MB=1024*1024;
const PLAN_STORAGE={Free:100*MB,'Student+':2048*MB,Power:4096*MB};
const ALLOWED_TYPES=new Set(['text','postLink','savedPost','attachment']);

const text=(value,max,required=false)=>{const result=String(value??'').trim();if(result.length>max||(required&&!result))throw new HttpsError('invalid-argument','Some submitted content is invalid.');return result;};
const signedIn=request=>{if(!request.auth?.uid)throw new HttpsError('unauthenticated','Sign in before trying this action.');return request.auth.uid;};
async function activeAccount(uid){const snapshot=await db.doc(`users/${uid}`).get();if(!snapshot.exists||snapshot.data().deactivated===true)throw new HttpsError('permission-denied','This account is unavailable.');return snapshot.data();}
async function planFor(uid){const snapshot=await db.doc(`entitlements/${uid}`).get();if(!snapshot.exists)return {name:'Free',storageBytes:PLAN_STORAGE.Free};const value=snapshot.data();const active=['Student+','Power'].includes(value.plan)&&value.expiresAt?.toMillis?.()>Date.now();const name=active?value.plan:'Free';return {name,storageBytes:PLAN_STORAGE[name]+Math.max(0,Number(value.storageAddonMB)||0)*MB};}
async function consumeRate(transaction,uid,action,limit,windowMs){const ref=db.doc(`rateLimits/${uid}_${action}`);const snapshot=await transaction.get(ref);const now=Date.now();const old=snapshot.exists?snapshot.data():null;const started=old?.windowStartedAt?.toMillis?.()||0;const reset=!old||now-started>=windowMs;const count=reset?1:Number(old.count||0)+1;if(count>limit)throw new HttpsError('resource-exhausted','Please wait before trying again.');return {ref,data:{uid,action,count,windowStartedAt:reset?Timestamp.now():old.windowStartedAt,updatedAt:FieldValue.serverTimestamp()}};}
async function consumeVoice(transaction,uid,targetId,hasVoice,plan){if(!hasVoice||plan!=='Free')return null;const day=new Date().toISOString().slice(0,10);const ref=db.doc(`voiceUsage/${uid}_${day}`);const snapshot=await transaction.get(ref);const count=Number(snapshot.data()?.count||0)+1;if(count>10)throw new HttpsError('resource-exhausted','Daily voice-note allowance reached.');return {ref,data:{uid,day,count,lastTargetId:targetId,updatedAt:FieldValue.serverTimestamp()}};}
const canonicalConversation=(participants)=>participants.length===1?`saved_${participants[0]}`:[...participants].sort().join('_');
const cleanFile=value=>{if(!value||typeof value!=='object')return null;return {name:text(value.name,180,true),meta:text(value.meta,80),type:text(value.type,100,true),url:text(value.url,500,true),...(Number.isFinite(Number(value.duration))?{duration:Math.max(0,Math.min(600,Number(value.duration)))}:{})};};
const cleanPostSnapshot=value=>{if(!value||typeof value!=='object')return null;return {id:text(value.id,160,true),course:text(value.course,120),author:text(value.author,80),authorId:text(value.authorId,160),text:text(value.text,4000),images:Array.isArray(value.images)?value.images.slice(0,10).map(item=>text(item,500,true)):[],imagePreviews:Array.isArray(value.imagePreviews)?value.imagePreviews.slice(0,2).map(item=>text(item,5000,true)):[],audioURL:value.audioURL?text(value.audioURL,500):null,files:Array.isArray(value.files)?value.files.slice(0,10).map(cleanFile).filter(Boolean):[]};};
const secureRef=(value,prefix)=>!value||String(value).startsWith(prefix);
const assertSecureFiles=(files,prefix)=>{if(files.some(file=>!secureRef(file?.url,prefix)))throw new HttpsError('invalid-argument','An attachment does not belong to this upload.');};
async function uploadHeader(bucket,path){return new Promise((resolve,reject)=>{const chunks=[];const stream=bucket.file(path).createReadStream({start:0,end:31});stream.on('data',chunk=>chunks.push(chunk));stream.on('end',()=>resolve(Buffer.concat(chunks)));stream.on('error',reject);});}
function signatureMatches(contentType,buffer){const type=String(contentType||'').toLowerCase();const hex=buffer.toString('hex');const ascii=buffer.toString('ascii');if(type==='application/pdf')return ascii.startsWith('%PDF-');if(['application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'].includes(type))return hex.startsWith('504b0304');if(type==='image/jpeg')return hex.startsWith('ffd8ff');if(type==='image/png')return hex.startsWith('89504e470d0a1a0a');if(type==='image/webp')return ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WEBP';if(type==='audio/ogg')return ascii.startsWith('OggS');if(type==='audio/wav')return ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WAVE';if(type==='audio/webm')return hex.startsWith('1a45dfa3');if(type==='audio/mpeg')return ascii.startsWith('ID3')||buffer[0]===0xff;if(type==='audio/mp4')return ascii.slice(4,8)==='ftyp';if(type==='application/msword')return hex.startsWith('d0cf11e0a1b11ae1');if(['application/vnd.ms-powerpoint','application/vnd.ms-excel'].includes(type))return hex.startsWith('d0cf11e0a1b11ae1');if(type==='text/plain')return !buffer.includes(0);return false;}

exports.ensureConversation=onCall({region:REGION},async request=>{const uid=signedIn(request);await activeAccount(uid);const participants=[...new Set((Array.isArray(request.data?.participants)?request.data.participants:[]).map(String))];if(![1,2].includes(participants.length)||!participants.includes(uid))throw new HttpsError('invalid-argument','Conversation participants are invalid.');const conversationId=canonicalConversation(participants);if(participants.length===2){const peer=participants.find(id=>id!==uid);const [a,b,profile]=await Promise.all([db.doc(`blocks/${uid}_${peer}`).get(),db.doc(`blocks/${peer}_${uid}`).get(),db.doc(`publicProfiles/${peer}`).get()]);if(a.exists||b.exists)throw new HttpsError('permission-denied','Messaging is unavailable for this conversation.');if(!profile.exists)throw new HttpsError('not-found','The recipient is unavailable.');}const ref=db.doc(`conversations/${conversationId}`);await db.runTransaction(async transaction=>{const existing=await transaction.get(ref);if(existing.exists&&canonicalConversation(existing.data().participants||[])!==conversationId)throw new HttpsError('permission-denied','Conversation is unavailable.');if(!existing.exists)transaction.create(ref,{participants,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});});return {conversationId};});

exports.createMessage=onCall({region:REGION},async request=>{
  const uid=signedIn(request);await activeAccount(uid);const input=request.data||{};
  const participants=[...new Set((Array.isArray(input.participants)?input.participants:[]).map(String))];
  if(![1,2].includes(participants.length)||!participants.includes(uid)||(participants.length===1&&participants[0]!==uid))throw new HttpsError('invalid-argument','Conversation participants are invalid.');
  const conversationId=canonicalConversation(participants);if(input.conversationId!==conversationId)throw new HttpsError('invalid-argument','Conversation is invalid.');
  const type=String(input.type||'text');if(!ALLOWED_TYPES.has(type))throw new HttpsError('invalid-argument','Message type is invalid.');
  const messageRef=db.collection('messages').doc();const conversationRef=db.doc(`conversations/${conversationId}`);const plan=await planFor(uid);let peer='';
  if(participants.length===2){peer=participants.find(id=>id!==uid);const [a,b,profile]=await Promise.all([db.doc(`blocks/${uid}_${peer}`).get(),db.doc(`blocks/${peer}_${uid}`).get(),db.doc(`publicProfiles/${peer}`).get()]);if(a.exists||b.exists)throw new HttpsError('permission-denied','Messaging is unavailable for this conversation.');if(!profile.exists)throw new HttpsError('not-found','The recipient is unavailable.');}
  const file=input.file?cleanFile(input.file):null;const post=input.post?cleanPostSnapshot(input.post):null;if(participants.length===2&&file?.type.startsWith('audio/'))throw new HttpsError('invalid-argument','Voice notes are not available in private messages.');if(file&&!secureRef(file.url,`conversations/${conversationId}/${uid}/`)&&!/^https:\/\/firebasestorage\.googleapis\.com\//i.test(file.url))throw new HttpsError('invalid-argument','The attachment does not belong to this conversation.');const message={conversationId,participants,senderId:uid,text:text(input.text,4000),type,seenBy:[uid],createdAt:FieldValue.serverTimestamp()};
  if(file)message.file=file;if(post)message.post=post;if(input.postId)message.postId=text(input.postId,160);if(input.replyTo&&typeof input.replyTo==='object')message.replyTo={id:text(input.replyTo.id,160,true),sender:text(input.replyTo.sender,80),text:text(input.replyTo.text,300)};if(file?.type.startsWith('audio/'))message.playedBy=[uid];
  await db.runTransaction(async transaction=>{const conversation=await transaction.get(conversationRef);if(conversation.exists&&canonicalConversation(conversation.data().participants||[])!==conversationId)throw new HttpsError('permission-denied','Conversation is unavailable.');const rate=await consumeRate(transaction,uid,'message',20,60_000);const voice=await consumeVoice(transaction,uid,messageRef.id,Boolean(file?.type.startsWith('audio/'))&&participants.length===1,plan.name);transaction.set(rate.ref,rate.data);if(voice)transaction.set(voice.ref,voice.data,{merge:true});if(!conversation.exists)transaction.create(conversationRef,{participants,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});else transaction.update(conversationRef,{updatedAt:FieldValue.serverTimestamp()});transaction.create(messageRef,message);});
  if(peer)await db.doc(`users/${peer}/notifications/${messageRef.id}`).set({type:'message',messageId:messageRef.id,senderId:uid,title:'New message',body:type==='attachment'?'Sent you a file':type==='postLink'?'Shared a post with you':message.text.slice(0,180)||'New message',read:false,createdAt:FieldValue.serverTimestamp()});
  return {id:messageRef.id};
});

exports.createComment=onCall({region:REGION},async request=>{
  const uid=signedIn(request);const profile=await activeAccount(uid);const input=request.data||{};const postId=text(input.postId,160,true);const postRef=db.doc(`posts/${postId}`);const post=await postRef.get();if(!post.exists)throw new HttpsError('not-found','Post not found.');const channelId=String(post.data().channelId||'');const membership=await db.doc(`memberships/${uid}_${channelId}`).get();const channel=await db.doc(`channels/${channelId}`).get();if(!membership.exists&&channel.data()?.ownerId!==uid)throw new HttpsError('permission-denied','Join the channel before commenting.');
  const commentRef=postRef.collection('comments').doc();const plan=await planFor(uid);const parentId=input.parentId?text(input.parentId,160):null;if(parentId){const parent=await postRef.collection('comments').doc(parentId).get();if(!parent.exists||parent.data().parentId)throw new HttpsError('invalid-argument','Replies are limited to one level.');}
  const comment={authorId:uid,author:text(profile.username,80,true),authorPhotoURL:text(profile.photoURL,500),text:text(input.text,2000),imageURL:input.imageURL?text(input.imageURL,500):null,audioURL:input.audioURL?text(input.audioURL,500):null,audioDuration:Math.max(0,Math.min(600,Number(input.audioDuration)||0)),parentId,createdAt:FieldValue.serverTimestamp()};const commentPrefix=`channels/${channelId}/comments/${postId}/${commentRef.id}/${uid}/`;if(!secureRef(comment.imageURL,commentPrefix)||!secureRef(comment.audioURL,commentPrefix))throw new HttpsError('invalid-argument','The attachment does not belong to this comment.');if(!comment.text&&!comment.imageURL&&!comment.audioURL)throw new HttpsError('invalid-argument','Comment content is required.');
  await db.runTransaction(async transaction=>{const rate=await consumeRate(transaction,uid,'comment',15,60_000);const voice=await consumeVoice(transaction,uid,commentRef.id,Boolean(comment.audioURL),plan.name);transaction.set(rate.ref,rate.data);if(voice)transaction.set(voice.ref,voice.data,{merge:true});transaction.create(commentRef,comment);transaction.update(postRef,{comments:FieldValue.increment(1)});});return {id:commentRef.id};
});

exports.deleteComment=onCall({region:REGION},async request=>{const uid=signedIn(request);await activeAccount(uid);const postId=text(request.data?.postId,160,true);const commentId=text(request.data?.commentId,160,true);const postRef=db.doc(`posts/${postId}`);const commentRef=postRef.collection('comments').doc(commentId);let channelId='';await db.runTransaction(async transaction=>{const [post,comment]=await Promise.all([transaction.get(postRef),transaction.get(commentRef)]);if(!comment.exists)return;if(comment.data().authorId!==uid&&!request.auth.token.admin)throw new HttpsError('permission-denied','You cannot delete this comment.');channelId=String(post.data()?.channelId||'');transaction.delete(commentRef);if(post.exists)transaction.update(postRef,{comments:Math.max(0,Number(post.data().comments||0)-1)});});if(channelId)await getStorage().bucket().deleteFiles({prefix:`channels/${channelId}/comments/${postId}/${commentId}/`}).catch(()=>{});return {deleted:true};});

exports.createPost=onCall({region:REGION,timeoutSeconds:60},async request=>{
  const uid=signedIn(request);const profile=await activeAccount(uid);const input=request.data||{};const channelId=text(input.channelId,160,true);const channelRef=db.doc(`channels/${channelId}`);const [channel,membership,plan]=await Promise.all([channelRef.get(),db.doc(`memberships/${uid}_${channelId}`).get(),planFor(uid)]);if(!channel.exists||(!membership.exists&&channel.data().ownerId!==uid))throw new HttpsError('permission-denied','Join the channel before publishing.');
  const postId=text(input.id,160,true);const postRef=db.doc(`posts/${postId}`);const images=Array.isArray(input.images)?input.images.slice(0,10).map(item=>text(item,500,true)):[];const files=Array.isArray(input.files)?input.files.slice(0,10).map(cleanFile).filter(Boolean):[];if(images.length+files.length>10)throw new HttpsError('invalid-argument','Too many attachments.');const post={id:postId,initials:text(input.initials,4),authorId:uid,author:text(profile.username,80,true),authorPhotoURL:text(profile.photoURL,500),ago:'now',course:text(channel.data().name,120),channelId,icon:text(channel.data().icon||'SL',4),text:text(input.text,4000),comments:0,images,imagePreviews:Array.isArray(input.imagePreviews)?input.imagePreviews.slice(0,2).map(item=>text(item,5000,true)):[],audioURL:input.audioURL?text(input.audioURL,500):null,audioDuration:Math.max(0,Math.min(600,Number(input.audioDuration)||0)),files,createdAt:FieldValue.serverTimestamp()};const postPrefix=`channels/${channelId}/posts/${postId}/${uid}/`;if(images.some(item=>!secureRef(item,postPrefix))||!secureRef(post.audioURL,postPrefix))throw new HttpsError('invalid-argument','An attachment does not belong to this post.');assertSecureFiles(files,postPrefix);if(!post.text&&!images.length&&!files.length&&!post.audioURL)throw new HttpsError('invalid-argument','Post content is required.');
  await db.runTransaction(async transaction=>{const rate=await consumeRate(transaction,uid,'post',5,60_000);const voice=await consumeVoice(transaction,uid,postId,Boolean(post.audioURL),plan.name);transaction.set(rate.ref,rate.data);if(voice)transaction.set(voice.ref,voice.data,{merge:true});transaction.create(postRef,post);});
  const members=await db.collection('memberships').where('channelId','==',channelId).get();const recipients=new Set(members.docs.map(doc=>doc.data().uid));recipients.add(channel.data().ownerId);recipients.delete(uid);for(const recipient of recipients){const setting=await db.doc(`users/${recipient}/channelSettings/${channelId}`).get();if(setting.data()?.muted===true)continue;await db.doc(`users/${recipient}/notifications/post_${postId}`).set({type:'channelPost',postId,channelId,title:`New post in #${channel.data().name}`,body:post.text.slice(0,180)||'New learning content',read:false,createdAt:FieldValue.serverTimestamp()});}
  return {id:postId};
});

exports.setSavedPost=onCall({region:REGION},async request=>{
  const uid=signedIn(request);await activeAccount(uid);const postId=text(request.data?.postId,160,true);const saved=Boolean(request.data?.saved);const ref=db.doc(`users/${uid}/saved/${postId}`);const usageRef=db.doc(`usage/${uid}`);const plan=await planFor(uid);let initialCount=null;if(!(await usageRef.get()).exists){const aggregate=await db.collection(`users/${uid}/saved`).count().get();initialCount=aggregate.data().count;}
  await db.runTransaction(async transaction=>{const [existing,usage]=await Promise.all([transaction.get(ref),transaction.get(usageRef)]);let count=usage.exists?Number(usage.data().savedCount||0):Number(initialCount||0);if(saved&&!existing.exists){count+=1;if(plan.name==='Free'&&count>7)throw new HttpsError('resource-exhausted','Free accounts can save up to seven posts.');transaction.create(ref,{postId,savedAt:FieldValue.serverTimestamp()});}else if(!saved&&existing.exists){count=Math.max(0,count-1);transaction.delete(ref);}transaction.set(usageRef,{uid,savedCount:count,updatedAt:FieldValue.serverTimestamp()},{merge:true});});return {saved};
});

exports.deletePost=onCall({region:REGION,timeoutSeconds:120},async request=>{const uid=signedIn(request);await activeAccount(uid);const postId=text(request.data?.postId,160,true);const ref=db.doc(`posts/${postId}`);const post=await ref.get();if(!post.exists)return {deleted:true};if(post.data().authorId!==uid&&!request.auth.token.admin)throw new HttpsError('permission-denied','You cannot delete this post.');await db.recursiveDelete(ref);await getStorage().bucket().deleteFiles({prefix:`channels/${post.data().channelId}/posts/${postId}/`}).catch(()=>{});await getStorage().bucket().deleteFiles({prefix:`users/${uid}/posts/${postId}/`}).catch(()=>{});return {deleted:true};});

exports.deleteChannel=onCall({region:REGION,timeoutSeconds:300},async request=>{const uid=signedIn(request);await activeAccount(uid);const channelId=text(request.data?.channelId,160,true);const channelRef=db.doc(`channels/${channelId}`);const channel=await channelRef.get();if(!channel.exists)return {deleted:true};if(channel.data().ownerId!==uid&&!request.auth.token.admin)throw new HttpsError('permission-denied','You cannot delete this channel.');const memberships=await db.collection('memberships').where('channelId','==',channelId).get();if(memberships.docs.some(doc=>doc.data().uid!==uid))throw new HttpsError('failed-precondition','Remove all other members before deleting this channel.');const posts=await db.collection('posts').where('channelId','==',channelId).get();for(const post of posts.docs)await db.recursiveDelete(post.ref);for(const member of memberships.docs)await member.ref.delete();await channelRef.delete();await getStorage().bucket().deleteFiles({prefix:`channels/${channelId}/`}).catch(()=>{});return {deleted:true};});

exports.deactivateAccount=onCall({region:REGION},async request=>{const uid=signedIn(request);await db.doc(`users/${uid}`).update({deactivated:true,updatedAt:FieldValue.serverTimestamp()});await getAuth().updateUser(uid,{disabled:true});await getAuth().revokeRefreshTokens(uid);return {deactivated:true};});

exports.setEntitlement=onCall({region:REGION},async request=>{const adminUid=signedIn(request);if(request.auth.token.admin!==true)throw new HttpsError('permission-denied','Administrator access is required.');const userId=text(request.data?.userId,160,true);const plan=text(request.data?.plan,20,true);if(!['Free','Student+','Power'].includes(plan))throw new HttpsError('invalid-argument','Plan is invalid.');const target=await getAuth().getUser(userId).catch(()=>null);if(!target)throw new HttpsError('not-found','Account not found.');const now=Timestamp.now();const expiresAt=plan==='Free'?null:Timestamp.fromMillis(Date.now()+30*24*60*60*1000);const entitlement={plan,storageAddonMB:0,expiresAt,source:'admin',updatedAt:FieldValue.serverTimestamp()};const batch=db.batch();batch.set(db.doc(`entitlements/${userId}`),entitlement,{merge:true});batch.create(db.collection('adminAuditLogs').doc(),{action:'setEntitlement',adminUid,targetUid:userId,plan,expiresAt,createdAt:FieldValue.serverTimestamp()});await batch.commit();return {plan,expiresAt:expiresAt?.toMillis?.()||null,updatedAt:now.toMillis()};});

exports.onUploadFinalized=onObjectFinalized({region:STORAGE_REGION,bucket:STORAGE_BUCKET},async event=>{const object=event.data;const uid=object.metadata?.ownerUid;const path=object.name;if(!uid||!path)return;const bucket=getStorage().bucket(object.bucket);const header=await uploadHeader(bucket,path).catch(()=>Buffer.alloc(0));if(!header.length||!signatureMatches(object.contentType,header)){await bucket.file(path).delete({ignoreNotFound:true});return;}const size=Math.max(0,Number(object.size)||0);const key=crypto.createHash('sha256').update(path).digest('hex');const ledger=db.doc(`storageObjects/${key}`);const usage=db.doc(`usage/${uid}`);const plan=await planFor(uid);let accepted=false;await db.runTransaction(async transaction=>{const [known,current]=await Promise.all([transaction.get(ledger),transaction.get(usage)]);if(known.exists){accepted=known.data().counted===true;return;}const used=Math.max(0,Number(current.data()?.storageBytes)||0);accepted=used+size<=plan.storageBytes;transaction.create(ledger,{uid,path,size,contentType:object.contentType||'',scanStatus:'signature-verified',counted:accepted,deleted:false,createdAt:FieldValue.serverTimestamp()});if(accepted)transaction.set(usage,{uid,storageBytes:used+size,updatedAt:FieldValue.serverTimestamp()},{merge:true});});if(!accepted)await bucket.file(path).delete({ignoreNotFound:true});});

exports.onUploadDeleted=onObjectDeleted({region:STORAGE_REGION,bucket:STORAGE_BUCKET},async event=>{const object=event.data;const path=object.name;if(!path)return;const key=crypto.createHash('sha256').update(path).digest('hex');const ledger=db.doc(`storageObjects/${key}`);await db.runTransaction(async transaction=>{const record=await transaction.get(ledger);if(!record.exists||record.data().deleted)return;const data=record.data();const usage=db.doc(`usage/${data.uid}`);const current=data.counted?await transaction.get(usage):null;transaction.update(ledger,{deleted:true,deletedAt:FieldValue.serverTimestamp()});if(data.counted)transaction.set(usage,{uid:data.uid,storageBytes:Math.max(0,Number(current.data()?.storageBytes||0)-Number(data.size||0)),updatedAt:FieldValue.serverTimestamp()},{merge:true});});});
