import { initializeApp } from 'firebase/app';
import * as auth from 'firebase/auth';
import * as firestoreApi from 'firebase/firestore';

const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const app=document.querySelector('#app');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api;
async function services(){if(api)return api;const firebase=initializeApp(config);api={auth,firestoreApi,instance:auth.getAuth(firebase),firestore:firestoreApi.getFirestore(firebase)};return api;}
function login(error=''){app.innerHTML=`<div class="wrap"><div class="card" style="max-width:420px;margin:8vh auto"><div class="brand"><img src="/studyloop-logo.png" alt="" />StudyLoop Admin</div><p class="muted">Sign in with an account granted the Firebase <code>admin</code> custom claim.</p><form id="login"><label class="field">Email<input name="email" type="email" autocomplete="username" required /></label><label class="field">Password<input name="password" type="password" autocomplete="current-password" required /></label><button class="button">Sign in</button>${error?`<p class="error">${esc(error)}</p>`:''}</form></div></div>`;document.querySelector('#login').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const s=await services();await s.auth.signInWithEmailAndPassword(s.instance,data.get('email'),data.get('password'));}catch(err){login('Unable to sign in.');}});}
async function dashboard(user){const s=await services();const token=await user.getIdTokenResult(true);if(token.claims.admin!==true){await s.auth.signOut(s.instance);login('This account is not an administrator.');return;}const [reports,users,posts,entitlements]=await Promise.all([s.firestoreApi.getDocs(s.firestoreApi.collection(s.firestore,'reports')),s.firestoreApi.getDocs(s.firestoreApi.collection(s.firestore,'users')),s.firestoreApi.getDocs(s.firestoreApi.collection(s.firestore,'posts')),s.firestoreApi.getDocs(s.firestoreApi.collection(s.firestore,'entitlements'))]);const planByUser=new Map(entitlements.docs.map(doc=>[doc.id,doc.data().plan]));app.innerHTML=`<div class="wrap"><header class="top"><div class="brand"><img src="/studyloop-logo.png" alt="" />StudyLoop Admin</div><button class="button secondary" id="logout">Sign out</button></header><section class="grid"><div class="card metric"><strong>${users.size}</strong><span>Accounts</span></div><div class="card metric"><strong>${posts.size}</strong><span>Posts</span></div><div class="card metric"><strong>${reports.size}</strong><span>Reports</span></div></section><section class="card"><h2>Account plans</h2><div class="stack">${users.docs.map(doc=>{const account=doc.data();const plan=planByUser.get(doc.id)||'Free';return `<div class="row"><span><strong>${esc(account.username)}</strong><br /><span class="muted">${esc(account.email)} · ${esc(plan)}</span></span><select data-plan-user="${esc(doc.id)}"><option ${plan==='Free'?'selected':''}>Free</option><option ${plan==='Student+'?'selected':''}>Student+</option><option ${plan==='Power'?'selected':''}>Power</option></select></div>`}).join('')}</div></section><section class="card"><h2>Reports</h2><div class="stack">${reports.docs.length?reports.docs.map(doc=>{const r=doc.data();return `<div class="row"><span><strong>${esc(r.type)}</strong> · ${esc(r.targetId)}<br /><span class="muted">${esc(r.reason)}</span></span><span class="muted">${esc(r.userId)}</span></div>`}).join(''):'<p class="muted">No reports.</p>'}</div></section></div>`;document.querySelector('#logout').onclick=()=>s.auth.signOut(s.instance);document.querySelectorAll('[data-plan-user]').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;try{await s.firestoreApi.setDoc(s.firestoreApi.doc(s.firestore,'entitlements',select.dataset.planUser),{plan:select.value,storageAddonMB:0,updatedAt:s.firestoreApi.serverTimestamp(),source:'admin'});select.disabled=false;}catch(error){select.disabled=false;alert('Unable to update this plan.');}}));}
async function start(){try{const s=await services();s.auth.onAuthStateChanged(user=>user?dashboard(user):login());}catch(error){login('Firebase configuration is missing or unavailable.');}}start();
