import { initializeApp } from 'firebase/app';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { getFirestore, collection, doc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore';

const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,storageBucket:import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};
const root=document.querySelector('#app');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const configured=Object.values(config).every(Boolean);
const firebase=configured?initializeApp(config):null;
const auth=firebase?getAuth(firebase):null;
const db=firebase?getFirestore(firebase):null;

function login(error=''){
  root.innerHTML=`<section class="shell"><form class="card login" id="login-form"><div class="brand"><img src="/studyloop-logo.png" alt="" />StudyLoop Admin</div><h1>Admin sign in</h1><p class="muted">Use your authorized StudyLoop account.</p><label class="field">Email<input name="email" type="email" autocomplete="username" required /></label><label class="field">Password<input name="password" type="password" autocomplete="current-password" required /></label><button class="button">Sign in</button>${error?`<p class="error">${escapeHtml(error)}</p>`:''}</form></section>`;
  document.querySelector('#login-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await signInWithEmailAndPassword(auth,String(form.get('email')).trim(),String(form.get('password')));}catch{login('Email or password is incorrect.');}});
}
async function dashboard(user){
  const token=await user.getIdTokenResult(true);if(token.claims.admin!==true){await signOut(auth);login('This account is not authorized for administration.');return;}
  try{const [users,posts,reports,entitlements]=await Promise.all(['users','posts','reports','entitlements'].map(name=>getDocs(collection(db,name))));const plans=new Map(entitlements.docs.map(item=>[item.id,item.data().plan||'Free']));root.innerHTML=`<main class="shell"><header class="top"><div class="brand"><img src="/studyloop-logo.png" alt="" />StudyLoop Admin</div><button class="button secondary" id="logout">Sign out</button></header><section class="grid"><article class="card metric"><strong>${users.size}</strong><span>Accounts</span></article><article class="card metric"><strong>${posts.size}</strong><span>Posts</span></article><article class="card metric"><strong>${reports.size}</strong><span>Reports</span></article></section><section class="card section"><h2>Account plans</h2>${users.docs.map(item=>{const account=item.data();const plan=plans.get(item.id)||'Free';return `<div class="row"><span><strong>${escapeHtml(account.username||'User')}</strong><br><small class="muted">${escapeHtml(account.email||'')}</small></span><select class="plan-select" data-user-id="${escapeHtml(item.id)}"><option ${plan==='Free'?'selected':''}>Free</option><option ${plan==='Student+'?'selected':''}>Student+</option><option ${plan==='Power'?'selected':''}>Power</option></select></div>`;}).join('')}</section><section class="card section"><h2>Reports</h2>${reports.docs.length?reports.docs.map(item=>`<div class="row"><span><strong>${escapeHtml(item.data().type||'Report')}</strong><br><small class="muted">${escapeHtml(item.data().reason||'')}</small></span></div>`).join(''):'<p class="muted">No reports.</p>'}</section></main>`;document.querySelector('#logout').onclick=()=>signOut(auth);document.querySelectorAll('[data-user-id]').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;try{await setDoc(doc(db,'entitlements',select.dataset.userId),{plan:select.value,storageAddonMB:0,source:'admin',updatedAt:serverTimestamp()},{merge:true});}catch{alert('Plan update was not allowed.');}finally{select.disabled=false;}}));}catch(error){console.error('Admin dashboard load failed.',error);root.innerHTML=`<section class="shell"><div class="card"><h1>Unable to load admin data</h1><p class="muted">Your account is signed in, but the dashboard data could not be loaded. Confirm the Firestore admin rules are deployed, then sign in again.</p><button class="button secondary" id="logout">Sign out</button></div></section>`;document.querySelector('#logout').onclick=()=>signOut(auth);}
}
if(!configured){login('Firebase configuration is unavailable. Start this portal from the StudyLoop admin folder.');}else onAuthStateChanged(auth,user=>user?dashboard(user):login());
